### ISSUE TITLE
Sample rate

### ISSUE THREAD

**Issue by ErazerBrecht** [ErazerBrecht/SensorTest#1]
Ari Perkkiö:
Acceleration:
We've been working a lot with the filters for the acceleration. At the moment it seems that it's not very accurate. Could you find out how high you can set the sampling rate for the acceleration measurements? In the demo app it looks like sampling rate isn't locked. I got various values from 7Hz to 80Hz. 
(Sampling rate, Fs = 1/[time(x+1) - time(x)] )

**Comment by ErazerBrecht** [comment]
Brecht
The sample rate is locked. But Android is just not able to keep a locked sample rate. It uses al the recources it can to keep the sample rate @ the same rate. 
So maybe you could try to shutdown some non important services...

I don't know what the relation is but can u change your auto rotation option and check if it's better?
On my tablet it gets better with auto rotation off with my phone it gets worser. But worth a shot :)

We are going to implement a textbox where we / you can check the sample rate.

**Comment by ErazerBrecht** [comment]
App that determines the sample rate of the device:
https://play.google.com/store/apps/details?id=cn.mountqi.sensor.rate.checker

**Comment by ErazerBrecht** [comment]
Graph sensor rate by Ari:
![lol](https://cloud.githubusercontent.com/assets/6287467/6575527/bea4ae0c-c72f-11e4-986d-6cd83f8113ea.PNG)

Conclusion: Still problems!

**Comment by Hannah93** [comment]
![image](https://cloud.githubusercontent.com/assets/11157825/6617866/788ad29a-c8bd-11e4-97cc-70a6e50b2190.png)

**Comment by ErazerBrecht** [comment]
Gooood news!
![image](https://cloud.githubusercontent.com/assets/6287467/6656747/36096458-cb34-11e4-99d8-ff2ffe34740d.png)

First try with new algorithm...
EDIT: Average is 51Hz

**Comment by ErazerBrecht** [comment]
![image](https://cloud.githubusercontent.com/assets/6287467/6656777/23a38478-cb35-11e4-8fc6-58757f20f100.png)

New scale...

**Comment by ErazerBrecht** [comment]
The new algorithm fixed this issue.
Writing the data to SD card was quite unstable.
This was the reason the sensor had delay so that the sensor rate wasn't stable.

Now we write to a list (RAM) and @ the end of the measurement we write to a file (SD).
This solved the problem!
